# Generated by Django 2.2 on 2019-05-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190504_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feautured',
            field=models.BooleanField(default=False),
        ),
    ]
