# Generated by Django 2.2.2 on 2019-07-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20190708_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=False, related_name='products', to='product.Category'),
        ),
    ]
