# Generated by Django 2.2.2 on 2019-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20190710_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=False, related_name='products', to='product.Category'),
        ),
    ]
