# Generated by Django 2.2.2 on 2019-06-22 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='c_password',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='password',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='username',
        ),
        migrations.AddField(
            model_name='reg',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='reg',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
