# Generated by Django 2.2.2 on 2019-06-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190622_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reg',
            name='username',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
