# Generated by Django 2.2.2 on 2019-06-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190622_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='profile_pic',
        ),
    ]
