# Generated by Django 2.2.2 on 2019-06-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190622_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='user',
        ),
        migrations.AlterField(
            model_name='reg',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
