# Generated by Django 2.0 on 2019-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190701_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
