# Generated by Django 2.0 on 2019-07-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_login_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
