# Generated by Django 2.2.3 on 2019-07-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190722_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
